---
title: "Iteration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get started 

```{r error = TRUE}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 6, sd = .3)

(x_-mean(x)) / sd(x)
(x_again-mean(x_again)) / sd(x_again)
```

Now a function 

```{r}
z_score = function(x) {
  
  if (!is.numeric(x)) {
    stop("x should be numeric")
  } else if (length(x < 3)) {
    stop("x should be longer than 3")
  }
  
  (x - mean(x))/ sd(x)
}
```

Trying out the function

```{r error = TRUE}
z_score(x = x_again)

z_score(x = 3) #doesnt work- single number

z_score(x = iris) #doesnt work- this is a df 


```

## Multiple Outputs

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x)
}
```

## test function

```{r}
mean_and_sd(x = x)
```

## multiple inputs 

```{r}

```


